version: 2.1
orbs:
  node: circleci/node@6.1.0
  heroku: circleci/heroku@2.0.0
jobs:

  validate-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm install bump-cli
      - when:
          condition:
            and:
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - deploy:
                name: Deploy bump documentation
                command: npm exec -- bump deploy bump.openapi.v3.yml
      - unless:
          condition:
            and:
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: Validate documentation
                command: npm exec -- bump deploy --dry-run bump.openapi.v3.yml  

  build:
    docker:
      - image: cimg/node:22.8.0

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test

  deploy_app:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          force: true
      - run:
          name: Run migrations
          command: |
            heroku run npm run migrate --app $HEROKU_APP_NAME || { echo 'Migration failed'; exit 1; }

  release:
    docker:
      - image: cimg/node:22.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run semantic-release
          command: npx semantic-release

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - deploy_app:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - release:
          filters:
            branches:
              only:
                - main
          requires:
            - build   
  bumpworkflow:
    jobs:
      - validate-deploy:
          filters:
            branches:
              only:
                - main